name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for scripts
        run: chmod +x bin/*.sh scripts/*.sh common/*.sh test/*.bats

      - name: Check files in scripts directory
        run: ls -l scripts

      - name: Print current working directory
        run: pwd

      - name: Install dependencies (Bats, jq, dos2unix)
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq dos2unix

      - name: Convert files to LF line endings
        run: find . -type f -exec dos2unix {} \;

      - name: Add bin directory to PATH
        run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Set BASE_DIR
        run: echo "BASE_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests
        run: bats test/*.bats
