name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for scripts
        run: chmod +x bin/*.sh scripts/*.sh common/*.sh test/*.bats

      - name: Install dependencies (Bats, jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq

      - name: Add bin directory to PATH
        run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Set BASE_DIR
        run: echo "BASE_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests
        run: bats test/*.bats
